# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad098eba167319d130fbd3e85ad6af15825351c05df9b11218fd96de87b100eedff2a5a31d0037ba99f4d26bdcf54a292b56b886508fd26cb23f445cfd343547

test:
  secret_key_base: 0c6bc39a7bd6f7f72573d0693d29c2a5578ab3fc43cdc8280fdebc0f0b8d32cab78961099f4f9b6a64eafc14d92c4c4b1191c984b5c21c48d8d95b027f62ef6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
